
const fs = require('fs');
const path = require('path');
const reverseMap = {
  "الدورات": "adminInstructors.courses",
  "المكتبة": "navbar.library",
  "من نحن": "navbar.about",
  "المؤسسات": "navbar.organizations",
  "الشراكات": "navbar.partnerships",
  "لوحة التحكم": "navbar.dashboard",
  "تسجيل الدخول": "login.signIn",
  "ابدأ الآن": "navbar.startNow",
  "تسجيل الخروج": "adminDashboard.logout",
  "مسؤول": "navbar.admin",
  "مدرب": "instructorOverview.instructor",
  "طالب": "common.students",
  "طوّر مهاراتك الهندسية": "hero.title1",
  "وابنِ مستقبلك": "hero.title2",
  "مسارات تعليمية منظمة، اختبارات تقييمية مستمرة، تتبع مباشر للتقدم، وشارات تحفزك للاستمرار. تعلّم من مهندسين ممارسين في سوق العمل الحقيقي.": "hero.subtitle",
  "ابدأ التعلم مجاناً": "hero.cta1",
  "استكشف الدورات": "about.exploreCourses",
  "دورات": "adminUsers.courses",
  "متدرب نشط": "hero.activeTrainees",
  "معدل الإنجاز": "hero.completionRate",
  "طاقة يومية": "hero.dailyEnergy",
  "سلسلة 12 يوم": "hero.streak",
  "شارة جديدة!": "hero.newBadge",
  "تم فتح متعلم سريع": "hero.fastLearner",
  "لماذا تختار المنصة": "features.label",
  "كل ما تحتاجه للتعلم الهندسي": "features.title",
  "مسارات منظمة": "features.structuredPaths",
  "منهج واضح ومُرتب من الدرس الأول حتى الاحتراف، لا مجال للتخمين حول الخطوة التالية.": "features.structuredPathsDesc",
  "تتبع التقدم": "features.trackProgress",
  "شاهد مدى تقدمك مع مقياس طاقة حي يرافقك في كل دورة تدريبية تشارك فيها.": "features.trackProgressDesc",
  "اختبار بعد كل فيديو": "features.quizAfterVideo",
  "ثبّت كل مفهوم لحظة انتهاء الدرس باختبار معرفي قصير ومركّز.": "features.quizAfterVideoDesc",
  "الأكثر تسجيلاً": "popularCourses.label",
  "دورات مميزة": "popularCourses.title",
  "تصفح الكل": "popularCourses.browseAll",
  "مكتبة المنصة": "topBooks.label",
  "الكتب": "topBooks.title1",
  "الأكثر تنزيلاً": "topBooks.title2",
  "أبرز الكتب التقنية والهندسية التي يختارها طلابنا ومتدربونا للتعلم والتطوير": "topBooks.subtitle",
  "لا توجد كتب متاحة بعد": "topBooks.noBooks",
  "تنزيل": "bookDetail.download",
  "بقلم": "topBooks.by",
  "كتاب تقني متميز من مكتبة المنصة.": "topBooks.bookDesc",
  "عرض الكتاب": "topBooks.viewBook",
  "تصفح المكتبة كاملة": "topBooks.browseLibrary",
  "هل أنت مستعد لشحن طاقتك؟": "cta.title",
  "انضم إلى آلاف المتعلمين الذين يبنون مهارات حقيقية جاهزة لسوق العمل. ابدأ مجاناً، وتعلم من خبراء يمارسون العمل فعلياً.": "cta.subtitle",
  "أنشئ حساب مجاني": "cta.createAccount",
  "تصفح الدورات": "studentDashboard.browseCourses",
  "سياسة الخصوصية": "footer.privacy",
  "سياسة الاستخدام": "footer.terms",
  "الدعم": "footer.support",
  "عمل الطلاب": "projects.label",
  "مشاريع بنيت": "projects.title1",
  "بواسطة متدربينا": "projects.title2",
  "مميز": "projects.featured",
  "بواسطة": "adminOverview.by",
  "تصفح جميع المشاريع": "projects.browseAll",
  "منصة رعاية صحية ذكية": "projects.project1Title",
  "منصة رعاية صحية ذكية تربط المرضى بالعيادات والأطباء والصيدليات في نظام موحد، مما يسهل حجز المواعيد والاستشارات عبر الإنترنت.": "projects.project1Desc",
  "روان قاعود": "projects.project1Author",
  "منصة Trainova": "projects.project2Title",
  "نظام قائم على الويب مصمم لربط الجامعات والطلاب ومؤسسات التدريب، يساعد في تنظيم عملية التدريب الداخلي بفعالية.": "projects.project2Desc",
  "راما البنا": "projects.project2Author",
  "طلباتي - Talabati": "projects.project3Title",
  "منصة إلكترونية ذكية لإدارة وتنظيم عمليات الطلب بين المتاجر والموردين (B2B)، تحول العمليات التقليدية لنظام رقمي.": "projects.project3Desc",
  "محمد الشامي": "projects.project3Author",
  "اختر...": "customSelect.placeholder",
  "لا توجد خيارات": "customSelect.noOptions",
  "[ رحلتنا ورؤيتنا ]": "about.label",
  "من نحن -": "about.title",
  "نحن لا نقدم مجرد دورات، بل نبني بيئة تعليمية متكاملة تهدف إلى تمكين جيل جديد من المهندسين والمبدعين في الوطن العربي بأحدث التقنيات وأفضل الأساليب التعليمية.": "about.intro",
  "رؤيتنا": "about.visionTitle",
  "أن نكون المنصة العربية الرائدة في تقديم التعليم الهندسي والتقني الاحترافي، وأن نساهم في سد الفجوة بين التعليم الأكاديمي واحتياجات سوق العمل الحديث من خلال محتوى عملي، تفاعلي، ومتجدد باستمرار.": "about.visionDesc",
  "رسالتنا": "about.missionTitle",
  "تمكين الأفراد من بناء مهارات حقيقية عبر توفير مكتبة ضخمة من الدورات التدريبية والمراجع العلمية، يديرها نخبة من الخبراء والمدربين، في بيئة تدعم التعلم المستمر والابتكار.": "about.missionDesc",
  "قيمنا الأساسية": "about.valuesTitle",
  "المبادئ التي تقود كل قرار نتخذه في المنصة لضمان تقديم أفضل تجربة ممكنة.": "about.valuesSubtitle",
  "الجودة والاحترافية": "about.quality",
  "نحرص على أن يكون كل محتوى يتم نشره على منصتنا خاضعاً لمعايير صارمة لضمان الدقة والفائدة العملية المباشرة.": "about.qualityDesc",
  "التعلم المستمر": "about.continuousLearning",
  "نؤمن بأن التطور التكنولوجي لا يتوقف، ولذلك نلتزم بتحديث دوراتنا ومكتبتنا لتواكب أحدث التقنيات باستمرار.": "about.continuousLearningDesc",
  "المجتمع الداعم": "about.community",
  "نبني مجتمعاً يتواصل فيه الطلاب والمدربون ليتبادلوا الخبرات ويساعدوا بعضهم البعض على تخطي العقبات.": "about.communityDesc",
  "هل أنت مستعد للبدء؟": "about.readyTitle",
  "انضم إلى آلاف الطلاب والمهندسين الذين بدؤوا رحلتهم نحو التميز مع منصتنا.": "about.readySubtitle",
  "أنشئ حساباً مجانياً": "about.createAccount",
  "الكل": "studentAssignments.all",
  "مبتدئ": "addCourse.beginner",
  "متوسط": "addCourse.intermediate",
  "متقدم": "addCourse.advanced",
  "مجاني": "courseDetail.free",
  "مدفوع": "courses.paid",
  "[ كتالوج الدورات ]": "courses.catalogLabel",
  "تصفّح كل الدورات": "courses.catalogTitle",
  "استكشف المكتبة كاملة عبر كل التصنيفات والمستويات. دورات جديدة كل أسبوع.": "courses.catalogSubtitle",
  "تصفية": "library.filter",
  "إعادة ضبط": "library.reset",
  "التصنيف": "adminAddBook.category",
  "المستوى": "addCourse.level",
  "السعر": "courseDetail.price",
  "دورة": "studentAssignments.course",
  "الترتيب: الأكثر رواجاً": "courses.sortPopular",
  "الترتيب: الأحدث": "courses.sortNewest",
  "لا توجد دورات مطابقة": "courses.noResults",
  "حاول تغيير خيارات التصفية أو إزالة بعضها.": "courses.noResultsHint",
  "إزالة التصفية": "library.clearFilters",
  "محاضرة": "courseDetail.lectures",
  "كتاب": "adminAddBook.book",
  "مرجع": "adminAddBook.reference",
  "بحث": "adminAddBook.research",
  "[ المكتبة الرقمية ]": "library.headerLabel",
  "تصفّح الكتب والمراجع": "library.headerTitle",
  "اكتشف آلاف الكتب، المراجع العلمية، والأبحاث لدعم مسيرتك التعليمية.": "library.headerSubtitle",
  "نوع الإصدار": "adminAddBook.publicationType",
  "ابحث عن اسم كتاب أو مؤلف...": "library.searchPlaceholder",
  "كتاب / مرجع": "library.bookCount",
  "الترتيب: الأكثر تقييماً": "library.sortRating",
  "الترتيب: الأحدث إضافة": "library.sortNewest",
  "صفحة": "bookDetail.pages",
  "قراءة الآن": "library.readNow",
  "لا توجد كتب مطابقة": "library.noResults",
  "حاول تغيير كلمات البحث أو خيارات التصفية.": "library.noResultsHint",
  "الكتاب غير موجود": "bookDetail.notFound",
  "← العودة للمكتبة": "bookDetail.backToLibrary",
  "رابط التنزيل غير متاح لهذا الكتاب بعد.": "bookDetail.noDownloadLink",
  "تنزيل الكتاب": "bookDetail.downloadBook",
  "العودة": "common.back",
  "الكتاب متاح للتنزيل": "bookDetail.availableForDownload",
  "اضغط زر التنزيل لبدء تحمِيل الملف مباشرة": "bookDetail.clickToDownload",
  "معلومات الكتاب": "bookDetail.bookInfo",
  "المؤلف": "adminAddBook.author",
  "النوع": "adminLibrary.type",
  "سنة النشر": "adminLibrary.publicationYear",
  "الدورة غير موجودة": "courseDetail.notFound",
  "← العودة للدورات": "courseDetail.backToCourses",
  "لديك هذه الدورة": "courseDetail.alreadyEnrolled",
  "جاري التسجيل...": "courseDetail.enrolling",
  "سجّل في الدورة": "courseDetail.enroll",
  "استكشف هذه الدورة التعليمية المتميزة وطوّر مهاراتك.": "courseDetail.courseDesc",
  "ماذا ستتعلم": "courseDetail.whatYouLearn",
  "محتوى الدورة": "addCourse.courseContent",
  "المحاضرة": "addCourse.lecture",
  "تفاصيل الدورة": "addCourse.courseDetails",
  "المدرب": "adminInstructors.instructor",
  "التقييم": "courseDetail.rating",
  "هذا الحساب ليس حساب طالب.": "login.notStudent",
  "هذا الحساب ليس حساب مدرب.": "login.notInstructor",
  "البريد الإلكتروني أو كلمة المرور غير صحيحة.": "adminLogin.invalidCredentials",
  "طور مهاراتك الهندسية وانطلق في مسيرتك": "login.heroTitle",
  "مسارات منظمة تدفعك نحو التميز.": "login.heroSubtitle",
  "مرحباً بعودتك!": "login.welcome",
  "اختر نوع حسابك وقم بتسجيل الدخول": "login.chooseAccount",
  "البريد الإلكتروني": "register.email",
  "كلمة المرور": "adminLogin.password",
  "نسيت كلمة المرور؟": "login.forgotPassword",
  "أو": "register.or",
  "ليس لديك حساب؟": "login.noAccount",
  "سجل الآن": "login.signUpNow",
  "يرجى إدخال الاسم الكامل": "register.nameRequired",
  "يرجى إدخال البريد الإلكتروني": "register.emailRequired",
  "كلمة المرور يجب أن تكون 6 أحرف على الأقل": "register.passwordMin",
  "كلمتا المرور غير متطابقتين": "register.passwordMismatch",
  "هذا البريد الإلكتروني مسجل مسبقاً.": "register.emailExists",
  "حدث خطأ في التسجيل، يرجى المحاولة لاحقاً.": "register.generalError",
  "انضم إلينا وابدأ رحلة التعلم": "register.heroTitle",
  "أنشئ حسابك الآن واستكشف مئات الدورات والمصادر.": "register.heroSubtitle",
  "إنشاء حساب جديد": "register.title",
  "أدخل بياناتك لإنشاء حسابك": "register.subtitle",
  "تم إنشاء الحساب بنجاح! جاري تحويلك لصفحة تسجيل الدخول...": "register.successStudent",
  "✅ تم إرسال طلب الانضمام! بانتظار موافقة الإدارة. سيتم إخطارك قريباً.": "register.successInstructor",
  "الاسم الكامل": "register.fullName",
  "أدخل اسمك الكامل": "register.fullNamePlaceholder",
  "6 أحرف على الأقل": "register.passwordHint",
  "تأكيد كلمة المرور": "register.confirmPassword",
  "أعد إدخال كلمة المرور": "register.confirmPasswordPlaceholder",
  "جاري الإنشاء...": "register.creating",
  "إنشاء الحساب": "register.createAccount",
  "سجل باستخدام Google": "register.googleSignUp",
  "لديك حساب بالفعل؟": "register.hasAccount",
  "سجل الدخول": "register.logIn",
  "هذا الحساب ليس حساب مسؤول.": "adminLogin.notAdmin",
  "لوحة تحكم المسؤول": "adminLogin.panelTitle",
  "تسجيل دخول المسؤول": "adminLogin.title",
  "أدخل بيانات حساب المسؤول للمتابعة": "adminLogin.subtitle",
  "اسم المستخدم": "adminLogin.username",
  "جاري الدخول...": "adminLogin.loggingIn",
  "دخول لوحة التحكم": "adminLogin.enter",
  "العودة للصفحة الرئيسية": "adminLogin.backHome",
  "عذراً، لقد فقدنا الاتصال!": "notFound.title",
  "يبدو أن الصفحة التي تبحث عنها غير موجودة، ربما تم تغيير الرابط أو تم حذفها. دعنا نعود إلى بر الأمان.": "notFound.subtitle",
  "العودة للرئيسية": "notFound.backHome",
  "الرجوع للخلف": "notFound.goBack",
  "المنصة. جميع الحقوق محفوظة.": "notFound.copyright",
  "غير مصرح بالدخول": "app.unauthorized",
  "هذه الصفحة مخصصة لنوع آخر من المستخدمين.": "app.unauthorizedDesc",
  "يرجى تسجيل الدخول من الصفحة المناسبة لحسابك.": "app.unauthorizedHint",
  "الذهاب لتسجيل دخول المدرب": "app.goInstructorLogin",
  "الذهاب لتسجيل دخول المسؤول": "app.goAdminLogin",
  "الذهاب لتسجيل دخول الطالب": "app.goStudentLogin",
  "طلبك قيد المراجعة": "app.pendingTitle",
  "تم إرسال طلب انضمامك كمدرب إلى الإدارة.": "app.pendingDesc",
  "سيتم إخطارك بعد موافقة المسؤول على طلبك.": "app.pendingHint",
  "يرجى المحاولة بعد بضع دقائق بعد موافقة الإدارة.": "app.pendingNote",
  "نظرة عامة": "instructorDashboard.overview",
  "الملف الشخصي": "instructorDashboard.profile",
  "التعلم": "studentDashboard.learning",
  "دوراتي": "submittedAssignments.myCourses",
  "الواجبات": "studentMyCourses.assignments",
  "التدريب والمشاريع": "studentDashboard.training",
  "غرفة العمل": "studentDashboard.workspace",
  "مشروعي": "studentDashboard.myProject",
  "معرض المشاريع": "studentDashboard.projectsShowcase",
  "إنجازاتي": "studentDashboard.achievements",
  "الإنجازات": "studentDashboard.achievementsSection",
  "شهاداتي": "studentDashboard.certificates",
  "لوحة تحكم الطالب": "studentDashboard.dashboardTitle",
  "أهلاً بعودتك،": "studentOverview.welcomeBack",
  "دورات قيد التقدّم": "studentOverview.coursesInProgress",
  "عرض الشهادة": "studentOverview.viewCertificate",
  "الشارات المكتسبة": "studentOverview.earnedBadges",
  "وقت التعلّم": "studentOverview.learningTime",
  "الفيديوهات المُشاهدة": "studentOverview.watchedVideos",
  "تابع التعلّم": "studentOverview.continueLearning",
  "لا توجد دورات قيد التقدم حالياً": "studentOverview.noCourses",
  "استكشف الدورات المتاحة": "studentOverview.exploreCourses",
  "عرض الكل": "instructorOverview.viewAll",
  "شارات حديثة": "studentOverview.recentBadges",
  "مفتوحة": "studentOverview.badgesUnlocked",
  "لا شارات بعد — أكمل مساراتك لتبدأ في جمعها.": "studentOverview.noBadges",
  "تصفح دورات جديدة": "studentMyCourses.browseNew",
  "الدورات التي سجّلت فيها وحالة تقدمك": "studentMyCourses.subtitle",
  "جاري التحميل...": "common.loading",
  "لم تسجّل في أي دورة بعد": "studentMyCourses.noCourses",
  "تصفح الدورات المتاحة": "studentMyCourses.browseCourses",
  "دورة غير معروفة": "studentMyCourses.unknownCourse",
  "مكتملة ✓": "studentMyCourses.completed",
  "مسار تعليمي": "studentMyCourses.learningTrack",
  "تعديل التقييم": "studentMyCourses.editRating",
  "إضافة تقييم": "studentMyCourses.addRating",
  "التقدم": "studentMyCourses.progress",
  "عرض الدورة": "studentMyCourses.viewCourse",
  "تقييم الدورة": "studentMyCourses.rateTitle",
  "إلغاء": "common.cancel",
  "جاري الحفظ...": "submittedAssignments.saving",
  "حفظ التقييم": "submittedAssignments.saveGrade",
  "بانتظار التسليم": "studentAssignments.pending",
  "تم التسليم": "studentAssignments.submitted",
  "تم التقييم": "studentAssignments.graded",
  "واجباتي": "studentAssignments.title",
  "واجب بانتظار التسليم": "studentAssignments.pendingCount",
  "لا توجد واجبات": "studentAssignments.noAssignments",
  "الدرجة:": "studentAssignments.grade",
  "تسليم الواجب": "studentAssignments.submit",
  "التفاصيل": "studentAssignments.details",
  "تفاصيل الواجب": "studentAssignments.detailsTitle",
  "عنوان الواجب": "submittedAssignments.assignmentTitle",
  "الدورة": "studentAssignments.courseName",
  "تاريخ التسليم": "submittedAssignments.submissionDate",
  "الوصف": "studentAssignments.description",
  "المرفقات": "submittedAssignments.attachments",
  "صورة تجريبية": "studentAssignments.demoImage",
  "الحالة": "adminInstructors.status",
  "إغلاق": "common.close",
  "محتوى الإجابة": "studentAssignments.answerContent",
  "اكتب إجابتك أو ملاحظاتك هنا...": "studentAssignments.answerPlaceholder",
  "إرفاق ملف (اختياري)": "studentAssignments.attachFile",
  "اضغط لاختيار ملف": "studentAssignments.clickToSelect",
  "جاري الإرسال...": "studentAssignments.sending",
  "إرسال التسليم": "studentAssignments.submitSolution",
  "م.": "instructorDashboard.eng",
  "إدارة الدورات": "adminCategories.parent",
  "لوحة تحكم المدرب": "instructorDashboard.dashboardTitle",
  "نظرة عامة على الإحصائيات": "instructorOverview.statsTitle",
  "أهلاً بك،": "instructorOverview.welcome",
  "إجمالي الطلاب": "adminOverview.totalStudents",
  "إدارة": "instructorOverview.manage",
  "دوراتك": "instructorOverview.yourCourses",
  "متوسط التقييم": "instructorOverview.avgRating",
  "إدارة دوراتي": "myCourses.title",
  "لا يوجد دورات مضافة حالياً.": "instructorOverview.noCourses",
  "تقييم": "instructorOverview.ratings",
  "تعديل": "common.edit",
  "لا توجد دورات مضافة بعد": "myCourses.noCourses",
  "تواصل مع الأدمن لإضافة دوراتك": "myCourses.contactAdmin",
  "مسودة": "adminCourses.draft",
  "غير محدد": "adminRequests.notSpecified",
  "إدارة الواجبات": "manageAssignments.title",
  "الواجبات المسلمة": "submittedAssignments.title",
  "تعديل الدورة": "editCourse.title",
  "عدّل تفاصيل الدورة ومحتواها": "editCourse.subtitle",
  "(لا يمكن تغيير العنوان أو المدرب أو التصنيف أو المستوى)": "editCourse.note",
  "عنوان الدورة": "addCourse.courseTitle",
  "(لا يمكن التعديل)": "editCourse.cannotEdit",
  "اختر المستوى": "addCourse.selectLevel",
  "عن الدورة": "addCourse.aboutCourse",
  "عدد المحاضرات": "addCourse.lectureCount",
  "أهداف الدورة": "addCourse.objectivesTitle",
  "أهداف": "addCourse.objectives",
  "محتوى الهدف ......": "editCourse.goalPlaceholder",
  "حذف الهدف": "addCourse.deleteGoal",
  "إضافة هدف": "addCourse.addGoal",
  "محاضرات": "addCourse.lecturesLabel",
  "تفاصيل المحاضرة": "addCourse.lectureDetails",
  "اضغط لفتح المحاضرة": "addCourse.clickToOpen",
  "حذف المحاضرة": "addCourse.deleteLecture",
  "فتح": "addCourse.open",
  "رقم المحاضرة": "addCourse.lectureNumber",
  "عنوان المحاضرة": "addCourse.lectureTitle",
  "اكتب عنوان المحاضرة": "addCourse.lectureTitlePlaceholder",
  "رابط المحاضرة": "addCourse.lectureLink",
  "أضف رابط المحاضرة": "addCourse.lectureLinkPlaceholder",
  "إضافة محاضرة": "addCourse.addLecture",
  "حفظ التعديلات": "editCourse.saveChanges",
  "هل أنت متأكد من حفظ التعديلات على هذه الدورة؟": "editCourse.confirmSave",
  "تأكيد الحفظ": "adminAddBook.confirmSaveBtn",
  "منشورة": "addCourse.published",
  "يرجى تعبئة كافة الحقول الأساسية (العنوان، المدرب، التصنيف)": "addCourse.requiredFields",
  "إضافة دورة": "adminCourses.addCourse",
  "أدخل كافة تفاصيل الدورة ومحتواها": "addCourse.subtitle",
  "عنوان البرنامج": "addCourse.courseTitlePlaceholder",
  "اختر المدرب": "addCourse.selectInstructor",
  "اختر تصنيف الدورة": "addCourse.selectCategory",
  "لا توجد تصنيفات. أضف تصنيفاً من صفحة تصنيفات الدورات أولاً.": "addCourse.noCategories",
  "اكتب نبذة عن الدورة...": "addCourse.aboutCoursePlaceholder",
  "حدد عدد المحاضرات": "addCourse.lectureCountPlaceholder",
  "محتوى الهدف ...": "addCourse.goalPlaceholder",
  "حفظ كمسودة": "addCourse.saveDraft",
  "حفظ الدورة": "addCourse.saveCourse",
  "إلغاء إضافة الدورة": "addCourse.cancelTitle",
  "هل أنت متأكد من حفظ الدورة وإضافتها إلى المنصة؟": "addCourse.confirmSavePublish",
  "هل أنت متأكد من حفظ الدورة كمسودة للعودة إليها لاحقاً؟": "addCourse.confirmSaveDraft",
  "هل أنت متأكد من إلغاء العملية؟ سيتم فقدان البيانات التي أدخلتها.": "addCourse.confirmCancel",
  "تأكيد الإلغاء": "adminAddBook.confirmCancelBtn",
  "إدارة واجبات الدورة": "manageAssignments.subtitle",
  "إضافة واجب جديد": "manageAssignments.addNew",
  "إضافة وحذف الواجبات الخاصة بهذه الدورة": "manageAssignments.addDeleteHint",
  "لا توجد واجبات بعد": "manageAssignments.noAssignments",
  "اضغط على \"إضافة واجب جديد\" لإنشاء أول واجب": "manageAssignments.noAssignmentsHint",
  "تاريخ التسليم:": "manageAssignments.dueDate",
  "تسليم": "manageAssignments.submissions",
  "حذف": "common.delete",
  "أدخل عنوان الواجب": "manageAssignments.assignmentTitlePlaceholder",
  "وصف الواجب": "manageAssignments.assignmentDesc",
  "اكتب وصفاً مفصلاً للواجب...": "manageAssignments.assignmentDescPlaceholder",
  "صورة توضيحية (اختياري)": "manageAssignments.illustrationImage",
  "اضغط لاختيار صورة": "manageAssignments.clickToChooseImage",
  "إضافة الواجب": "manageAssignments.addAssignment",
  "حذف الواجب": "manageAssignments.deleteTitle",
  "هل أنت متأكد من حذف هذا الواجب؟ لا يمكن التراجع عن هذا الإجراء.": "manageAssignments.deleteConfirm",
  "تأكيد الحذف": "adminLibraryCategories.confirmDelete",
  "معاينة الواجبات التي سلمها الطلاب": "submittedAssignments.subtitle",
  "إجمالي التسليمات": "submittedAssignments.totalSubmissions",
  "بانتظار المراجعة": "submittedAssignments.pendingReview",
  "تمت المراجعة": "submittedAssignments.reviewed",
  "اسم الطالب": "submittedAssignments.studentName",
  "الواجب": "submittedAssignments.assignment",
  "الإجراء": "submittedAssignments.action",
  "معاينة": "submittedAssignments.preview",
  "معاينة الواجب المسلّم": "submittedAssignments.previewTitle",
  "محتوى التسليم": "submittedAssignments.submissionContent",
  "لا يوجد نص.": "submittedAssignments.noText",
  "محتوى تجريبي للملف": "submittedAssignments.demoContent",
  "تقييم الواجب (من 100)": "submittedAssignments.gradeLabel",
  "أدخل العلامة...": "submittedAssignments.gradePlaceholder",
  "أدمن المنصة": "adminDashboard.adminTitle",
  "الإحصائيات الرئيسية": "adminOverview.mainStats",
  "إدارة المدربين": "adminRequests.parent",
  "طلبات الانضمام": "adminRequests.title",
  "قائمة المدربين": "adminInstructors.title",
  "إدارة الطلاب": "adminUsers.parent",
  "جميع الطلاب": "adminUsers.title",
  "قائمة الدورات": "adminDashboard.coursesList",
  "تصنيفات الدورات": "adminCategories.title",
  "إضافة دورة جديدة": "adminDashboard.addNewCourse",
  "إدارة المكتبة": "adminLibraryCategories.parent",
  "محتوى المكتبة": "adminDashboard.libraryContent",
  "تصنيفات المكتبة": "adminDashboard.libraryCategories",
  "إضافة كتاب/مرجع": "adminDashboard.addBook",
  "لوحة تحكم الأدمن": "adminDashboard.dashboardTitle",
  "المدربون النشطون": "adminOverview.activeInstructors",
  "الدورات المنشورة": "adminOverview.publishedCourses",
  "كتب المكتبة": "adminOverview.libraryBooks",
  "نظرة عامة على أداء المنصة اليوم": "adminOverview.statsSubtitle",
  "طلبات بانتظار المراجعة": "adminOverview.pendingRequests",
  "مدربين بانتظار موافقة الانضمام.": "adminOverview.pendingInstructors",
  "لا توجد طلبات انضمام تتطلب التدخل حالياً.": "adminOverview.noPendingRequests",
  "مراجعة الطلبات": "adminOverview.reviewRequests",
  "آخر النشاطات": "adminOverview.recentActivities",
  "دورة جديدة": "adminOverview.newCourse",
  "لا يوجد نشاطات حالياً.": "adminOverview.noActivities",
  "كل الدورات": "adminCourses.title",
  "إدارة الدورات المنشورة والمسودات على المنصة": "adminCourses.subtitle",
  "حذف الدورة": "adminCourses.deleteTitle",
  "هل تريد حذف «{title}»؟ لا يمكن التراجع عن هذا الإجراء.": "adminLibrary.deleteConfirm",
  "إدارة الكتب والمساقات": "adminLibrary.title",
  "راجع مراجع المكتبة الرقمية وأضف مصادر جديدة": "adminLibrary.subtitle",
  "إضافة كتاب": "adminLibrary.addBook",
  "تعديل بيانات الكتاب": "adminLibrary.editTitle",
  "عنوان الكتاب": "adminAddBook.bookTitle",
  "عدد الصفحات": "adminAddBook.pageCount",
  "حفظ التغييرات": "adminLibrary.saveChanges",
  "حذف الكتاب": "adminLibrary.deleteTitle",
  "يرجى تعبئة كافة الحقول الأساسية (العنوان، المؤلف، التصنيف)": "adminAddBook.requiredFields",
  "إضافة كتاب جديد": "adminAddBook.title",
  "أدخل بيانات الكتاب أو المرجع ثم احفظه في المكتبة": "adminAddBook.subtitle",
  "اسم الكتاب": "adminAddBook.bookTitlePlaceholder",
  "اسم المؤلف": "adminAddBook.authorPlaceholder",
  "اختر تصنيف الكتاب": "adminAddBook.selectCategory",
  "لا توجد تصنيفات. أضف تصنيفاً من صفحة تصنيفات الكتب أولاً.": "adminAddBook.noCategories",
  "أدخل عدد الصفحات": "adminAddBook.pageCountPlaceholder",
  "رابط الملف (Drive)": "adminAddBook.fileLink",
  "إضافة للمكتبة": "adminAddBook.addToLibrary",
  "حفظ الكتاب": "adminAddBook.saveBook",
  "إلغاء الإضافة": "adminAddBook.cancelTitle",
  "هل أنت متأكد من إضافة الكتاب إلى المكتبة؟": "adminAddBook.confirmSave",
  "سيتم فقدان البيانات التي أدخلتها.": "adminAddBook.confirmCancel",
  "هل أنت متأكد من حذف هذا الطالب نهائياً؟": "adminUsers.deleteConfirm",
  "حدث خطأ أثناء الحذف": "adminInstructors.deleteError",
  "ابحث عن الطلاب وتابع حالة حساباتهم": "adminUsers.subtitle",
  "ابحث بالاسم أو البريد...": "adminUsers.searchPlaceholder",
  "لا توجد نتائج مطابقة": "adminUsers.noResults",
  "تاريخ الانضمام:": "adminUsers.joinDate",
  "متوقف": "adminUsers.inactive",
  "نشط": "adminInstructors.active",
  "حذف الطالب": "adminUsers.deleteStudent",
  "هل أنت متأكد من حذف هذا المدرب نهائياً؟": "adminInstructors.deleteConfirm",
  "عرض كل المدربين المعتمدين على المنصة": "adminInstructors.subtitle",
  "التخصص": "adminInstructors.specialization",
  "الطلاب": "adminInstructors.students",
  "لا يوجد مدربين": "adminInstructors.noInstructors",
  "معلّق": "adminInstructors.pending",
  "تم قبول": "adminRequests.accepted",
  "تم رفض طلب": "adminRequests.rejected",
  "راجع طلبات المدربين الجدد ووافق عليها أو ارفضها": "adminRequests.subtitle",
  "لا توجد طلبات معلّقة حالياً": "adminRequests.noPending",
  "تخصص غير محدد": "adminRequests.unspecifiedSpecialization",
  "خبرة": "adminRequests.experience",
  "غير محددة": "adminRequests.unspecified",
  "قبول": "adminRequests.accept",
  "رفض": "adminRequests.reject",
  "أضف أو احذف التصنيفات التي تظهر عند إنشاء دورة جديدة": "adminCategories.subtitle",
  "مثال: تطوير الويب": "adminCategories.placeholder",
  "إضافة تصنيف": "adminLibraryCategories.add",
  "لا توجد تصنيفات بعد": "adminLibraryCategories.noCategories",
  "حذف التصنيف": "adminLibraryCategories.deleteTitle",
  "هل تريد حذف التصنيف؟ لن يُحذف المحتوى المرتبط به حالياً، لكنه لن يظهر في نماذج الإضافة.": "adminLibraryCategories.deleteConfirm",
  "تصنيفات الكتب": "adminLibraryCategories.title",
  "أضف أو احذف التصنيفات التي تظهر عند إضافة كتاب للمكتبة": "adminLibraryCategories.subtitle",
  "مثال: هندسة البرمجيات": "adminLibraryCategories.placeholder",
  "حفظ": "common.save",
  "تأكيد": "common.confirm",
  "من": "common.of"
};

const targetFiles = process.argv.slice(2);

for (const file of targetFiles) {
  let content = fs.readFileSync(file, 'utf8');
  let originalContent = content;

  // Add import if not present
  if (!content.includes('useLanguage')) {
    const isSubdir = file.includes('admin\\') || file.includes('admin/') || file.includes('student/') || file.includes('instructor/');
    const importPath = isSubdir ? '../../context/LanguageContext' : '../context/LanguageContext';
    
    // Find last import
    const lastImportIndex = content.lastIndexOf('import ');
    const nextLineIndex = content.indexOf('\n', lastImportIndex);
    if (nextLineIndex !== -1) {
      content = content.slice(0, nextLineIndex + 1) + `import { useLanguage } from '${importPath}';\n` + content.slice(nextLineIndex + 1);
    } else {
      content = `import { useLanguage } from '${importPath}';\n` + content;
    }
  }

  // Add const { t, dir } = useLanguage(); inside the component
  // Find component definition: const MyComponent = () => { or function MyComponent() {
  const compRegex = /(?:const\s+\w+\s*=\s*\([^)]*\)\s*=>\s*{|function\s+\w+\s*\([^)]*\)\s*{)/;
  const match = content.match(compRegex);
  if (match) {
    if (!content.includes('useLanguage()')) {
      const insertionPoint = match.index + match[0].length;
      content = content.slice(0, insertionPoint) + '\n  const { t, dir } = useLanguage();' + content.slice(insertionPoint);
    }
  }

  // Replace dir="rtl" with dir={dir}
  content = content.replace(/dir="rtl"/g, 'dir={dir}');

  // Now replace all strings.
  // We need to be careful with JSX text vs Attributes
  const sortedKeys = Object.keys(reverseMap).sort((a, b) => b.length - a.length);
  
  for (const arText of sortedKeys) {
    if (arText.trim() === '') continue;
    const key = reverseMap[arText];
    
    // 1. Replace >ArabicText< with >{t('key')}<
    const jsxRegex = new RegExp('>' + escapeRegExp(arText) + '\\s*<', 'g');
    content = content.replace(jsxRegex, '>{t(\'' + key + '\')}<');
    
    // 2. Replace placeholder="ArabicText" with placeholder={t('key')}
    const attrRegex = new RegExp('([a-zA-Z]+)="(' + escapeRegExp(arText) + ')"', 'g');
    content = content.replace(attrRegex, (match, p1, p2) => {
      return p1 + '={t(\'' + key + '\')}';
    });
    
    // 3. Replace >ArabicText with >{t('key')}
    // 4. Replace ArabicText< with {t('key')}<
    // Using a more generic approach: match the text outside tags, but it's tricky.
    // Let's just do generic replace for JSX if it's not inside quotes
    const genericJsxRegex = new RegExp('(?<=>[^<]*)' + escapeRegExp(arText) + '(?=[^>]*<)', 'g');
    content = content.replace(genericJsxRegex, '{t(\'' + key + '\')}');
  }

  if (content !== originalContent) {
    fs.writeFileSync(file, content, 'utf8');
    console.log('Modified', file);
  }
}

function escapeRegExp(string) {
  return string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
